## Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# Create a simple dataframe
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
## create an instance of onehotencoder
encoder = OneHotEncoder()

In [9]:
## perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray() #.toarray() converts that sparse matrix into a normal NumPy array:
# fit       → learns the categories
# transform → converts categories into numbers

In [ ]:
import pandas as pd
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out()) #get_feature_names_out()- This gives the encoded column names:

In [ ]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [13]:
# for new data
encoder.transform([['blue']]).toarray()

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [14]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [26]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [25]:
print(df.columns)

Index(['color'], dtype='str')

In [28]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder 
df = sns.load_dataset('tips') 
print(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [ ]:
encoder = OneHotEncoder()  # # Create encoder

In [ ]:
encoded = encoder.fit_transform(df[['day']]).toarray() # # Encode day

In [31]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [32]:
encoder_df

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [34]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [35]:
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [36]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [37]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [38]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [39]:
lbl_encoder.transform([['red']])

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [40]:
lbl_encoder.transform([['blue']])

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [41]:
lbl_encoder.transform([['green']])

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

### Ordinal Encoding
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [42]:
## ordinal encoding
from sklearn.preprocessing import OrdinalEncoder

In [43]:
# create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [44]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [45]:
# create an instance of ordinalencoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [46]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [47]:
encoder.transform([['small']])

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

#### Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [48]:
import pandas as pd
# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city':['New York',"London","Paris","Tokoyo","New York","Paris"],
    'price':[200,150,300,250,180,320]
})

In [49]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3    Tokoyo    250
4  New York    180
5     Paris    320

In [50]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [51]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokoyo': 250.0}

In [52]:
df['city_encoded'] = df['city'].map(mean_price)

In [54]:
df[['city','price','city_encoded']]

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3    Tokoyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [ ]:
import seaborn as sns
sns.load_dataset('tips')  # convert time into total_bill

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
mean_total_bill = df.groupby('time')['total_bill'].mean().to_dict()

In [62]:
mean_total_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [63]:
df['time_encoded'] = df['time'].map(mean_total_bill)

In [64]:
df[['total_bill','time']]

     total_bill    time
0         16.99  Dinner
1         10.34  Dinner
2         21.01  Dinner
3         23.68  Dinner
4         24.59  Dinner
..          ...     ...
239       29.03  Dinner
240       27.18  Dinner
241       22.67  Dinner
242       17.82  Dinner
243       18.78  Dinner

[244 rows x 2 columns]